export const TASK_GET_ALL_PERMISSION_START = "TASK_GET_ALL_PERMISSION_START";
export const TASK_GET_ALL_PERMISSION_COMPLETE = "TASK_GET_ALL_PERMISSION_COMPLETE";
export const TASK_GET_ALL_PERMISSION_END = "TASK_GET_ALL_PERMISSION_END";

export const TASK_LOAD_USER_START = "TASK_LOAD_USER_START";
export const TASK_LOAD_USER_COMPLETE = "TASK_LOAD_USER_COMPLETE";
export const TASK_LOAD_USER_END = "TASK_LOAD_USER_END";


export const TASK_LOAD_ALL_USER_START = "TASK_LOAD_ALL_USER_START";
export const TASK_LOAD_ALL_USER_COMPLETE = "TASK_LOAD_ALL_USER_COMPLETE";
export const TASK_LOAD_ALL_USER_END = "TASK_LOAD_ALL_USER_END";

export const TASK_LOAD_PACKAGE_START = "TASK_LOAD_PACKAGE_START";
export const TASK_LOAD_PACKAGE_COMPLETE = "TASK_LOAD_PACKAGE_COMPLETE";
export const TASK_LOAD_PACKAGE_END = "TASK_LOAD_PACKAGE_END";


export const TASK_DELETE_USER_START = "TASK_DELETE_USER_START";
export const TASK_DELETE_USER_COMPLETE = "TASK_DELETE_USER_COMPLETE";
export const TASK_DELETE_USER_END = "TASK_DELETE_USER_END";


export const TASK_RECOVER_USER_START = "TASK_RECOVER_USER_START";
export const TASK_RECOVER_USER_COMPLETE = "TASK_RECOVER_USER_COMPLETE";
export const TASK_RECOVER_USER_END = "TASK_RECOVER_USER_END";

export const TASK_RECOVER_PAYMENT_START = "TASK_RECOVER_PAYMENT_START";
export const TASK_RECOVER_PAYMENT_COMPLETE = "TASK_RECOVER_PAYMENT_COMPLETE";
export const TASK_RECOVER_PAYMENT_END = "TASK_RECOVER_PAYMENT_END";


export const TASK_LOAD_TEAM_START = "TASK_LOAD_TEAM_START";
export const TASK_LOAD_TEAM_COMPLETE = "TASK_LOAD_TEAM_COMPLETE";
export const TASK_LOAD_TEAM_END = "TASK_LOAD_TEAM_END";

export const TASK_REMOVE_TEAM_USER_START = "TASK_REMOVE_TEAM_USER_START";
export const TASK_REMOVE_TEAM_USER_COMPLETE = "TASK_REMOVE_TEAM_USER_COMPLETE";
export const TASK_REMOVE_TEAM_USER_END = "TASK_REMOVE_TEAM_USER_END";

export const TASK_INSERT_TEAM_USER_START = "TASK_INSERT_TEAM_USER_START";
export const TASK_INSERT_TEAM_USER_COMPLETE = "TASK_INSERT_TEAM_USER_COMPLETE";
export const TASK_INSERT_EMAIL_ERROR = "TASK_INSERT_EMAIL_ERROR";
export const TASK_INSERT_TEAM_USER_END = "TASK_INSERT_TEAM_USER_END";


export const TASK_LOAD_ROLE_START = "TASK_LOAD_ROLE_START";
export const TASK_LOAD_ROLE_COMPLETE = "TASK_LOAD_ROLE_COMPLETE";
export const TASK_LOAD_ROLE_END = "TASK_LOAD_ROLE_END";

export const TASK_LOAD_PAYMENT_START = "TASK_LOAD_PAYMENT_START";
export const TASK_LOAD_PAYMENT_COMPLETE = "TASK_LOAD_PAYMENT_COMPLETE";
export const TASK_LOAD_PAYMENT_END = "TASK_LOAD_PAYMENT_END";




export const TASK_LOAD_ENTERPRISE_START = "TASK_LOAD_ENTERPRISE_START";
export const TASK_LOAD_ENTERPRISE_COMPLETE = "TASK_LOAD_ENTERPRISE_COMPLETE";
export const TASK_LOAD_ENTERPRISE_END = "TASK_LOAD_ENTERPRISE_END";



export const TASK_LOGIN_USER_START = "TASK_LOGIN_USER_START";
export const TASK_LOGIN_USER_COMPLETE = "TASK_LOGIN_USER_COMPLETE";
export const TASK_LOGIN_USER_ERROR = "TASK_LOGIN_USER_ERROR";
export const TASK_LOGIN_USER_END = "TASK_LOGIN_USER_END";



export const TASK_LOAD_ALL_PACKAGE_START = "TASK_LOAD_ALL_PACKAGE_START";
export const TASK_LOAD_ALL_PACKAGE_COMPLETE = "TASK_LOAD_ALL_PACKAGE_COMPLETE";
export const TASK_LOAD_ALL_PACKAGE_END = "TASK_LOAD_ALL_PACKAGE_END";


// Work Order

export const TASK_LOAD_WORK_SITE_START = "TASK_LOAD_WORK_SITE_START";
export const TASK_LOAD_WORK_SITE_COMPLETE = "TASK_LOAD_WORK_SITE_COMPLETE";
export const TASK_LOAD_WORK_SITE_END = "TASK_LOAD_WORK_SITE_END";



export const TASK_LOAD_WORK_SITE_DOC_START = "TASK_LOAD_WORK_SITE_DOC_START";
export const TASK_LOAD_WORK_SITE_DOC_COMPLETE = "TASK_LOAD_WORK_SITE_DOC_COMPLETE";
export const TASK_LOAD_WORK_SITE_DOC_END = "TASK_LOAD_WORK_SITE_DOC_END";




export const TASK_LOAD_COMPANY_USER_START = "TASK_LOAD_COMPANY_USER_START";
export const TASK_LOAD_COMPANY_USER_COMPLETE = "TASK_LOAD_COMPANY_USER_COMPLETE";
export const TASK_LOAD_COMPANY_USER_END = "TASK_LOAD_COMPANY_USER_END";

export const TASK_DELETE_WORK_ORDER_START = "TASK_DELETE_WORK_ORDER_START";
export const TASK_DELETE_WORK_ORDER_COMPLETE = "TASK_DELETE_WORK_ORDER_COMPLETE";
export const TASK_DELETE_WORK_ORDER_END = "TASK_DELETE_WORK_ORDER_END";

export const TASK_LOAD_MY_WORK_ORDER_START = "TASK_LOAD_MY_WORK_ORDER_START";
export const TASK_LOAD_MY_WORK_ORDER_COMPLETE = "TASK_LOAD_MY_WORK_ORDER_COMPLETE";
export const TASK_LOAD_MY_WORK_ORDER_EXPIRED_ERROR = "TASK_LOAD_MY_WORK_ORDER_EXPIRED_ERROR";
export const TASK_LOAD_MY_WORK_ORDER_END = "TASK_LOAD_MY_WORK_ORDER_END";

export const TASK_LOAD_ASSIGEND_TO_ME_START = "TASK_LOAD_ASSIGEND_TO_ME_START";
export const TASK_LOAD_ASSIGEND_TO_ME_COMPLETE = "TASK_LOAD_ASSIGEND_TO_ME_COMPLETE";
export const TASK_LOAD_ASSIGEND_TO_ME_EXPIRED_ERROR = "TASK_LOAD_ASSIGEND_TO_ME_EXPIRED_ERROR";
export const TASK_LOAD_ASSIGEND_TO_ME_END = "TASK_LOAD_ASSIGEND_TO_ME_END";

export const TASK_LOAD_ARCHIVED_START = "TASK_LOAD_ARCHIVED_START";
export const TASK_LOAD_ARCHIVED_COMPLETE = "TASK_LOAD_ARCHIVED_COMPLETE";
export const TASK_LOAD_ARCHIVED_EXPIRED_ERROR = "TASK_LOAD_ARCHIVED_EXPIRED_ERROR";
export const TASK_LOAD_ARCHIVED_END = "TASK_LOAD_ARCHIVED_END";


export const TASK_APPROVE_WORK_ORDER_START = "TASK_APPROVE_WORK_ORDER_START";
export const TASK_APPROVE_WORK_ORDER_COMPLETE = "TASK_APPROVE_WORK_ORDER_COMPLETE";
export const TASK_APPROVE_WORK_ORDER_END = "TASK_APPROVE_WORK_ORDER_END";

export const TASK_DECLINE_WORK_ORDER_START = "TASK_DECLINE_WORK_ORDER_START";
export const TASK_DECLINE_WORK_ORDER_COMPLETE = "TASK_DECLINE_WORK_ORDER_COMPLETE";
export const TASK_DECLINE_WORK_ORDER_END = "TASK_DECLINE_WORK_ORDER_END";

export const TASK_ARCHIVE_WORK_ORDER_START = "TASK_ARCHIVE_WORK_ORDER_START";
export const TASK_ARCHIVE_WORK_ORDER_COMPLETE = "TASK_ARCHIVE_WORK_ORDER_COMPLETE";
export const TASK_ARCHIVE_WORK_ORDER_END = "TASK_ARCHIVE_WORK_ORDER_END";

export const TASK_UNARCHIVE_WORK_ORDER_START = "TASK_UNARCHIVE_WORK_ORDER_START";
export const TASK_UNARCHIVE_WORK_ORDER_COMPLETE = "TASK_UNARCHIVE_WORK_ORDER_COMPLETE";
export const TASK_UNARCHIVE_WORK_ORDER_END = "TASK_UNARCHIVE_WORK_ORDER_END";

export const TASK_COMPLETE_WORK_ORDER_START = "TASK_COMPLETE_WORK_ORDER_START";
export const TASK_COMPLETE_WORK_ORDER_COMPLETE = "TASK_COMPLETE_WORK_ORDER_COMPLETE";
export const TASK_COMPLETE_WORK_ORDER_END = "TASK_COMPLETE_WORK_ORDER_END";

export const TASK_GET_WORK_ORDER_BY_ID_START = "TASK_GET_WORK_ORDER_BY_ID_START";
export const TASK_GET_WORK_ORDER_BY_ID_COMPLETE = "TASK_GET_WORK_ORDER_BY_ID_COMPLETE";
export const TASK_GET_WORK_ORDER_BY_ID_END = "TASK_GET_WORK_ORDER_BY_ID_END";

export const TASK_CLEAR_EXPIRED = "TASK_CLEAR_EXPIRED";



export const TASK_GET_POI_START = "TASK_GET_POI_START";
export const TASK_GET_POI_ERROR = "TASK_GET_POI_ERROR";
export const TASK_GET_POI_COMPLETE = "TASK_GET_POI_COMPLETE";
export const TASK_GET_POI_END = "TASK_GET_POI_END";

export const TASK_GET_POI_ARCHIVED_START = "TASK_GET_POI_ARCHIVED_START";
export const TASK_GET_POI_ARCHIVED_COMPLETE = "TASK_GET_POI_ARCHIVED_COMPLETE";
export const TASK_GET_POI_ARCHIVED_END = "TASK_GET_POI_ARCHIVED_END";

export const TASK_GET_POI_DRAFT_START = "TASK_GET_POI_DRAFT_START";
export const TASK_GET_POI_DRAFT_COMPLETE = "TASK_GET_POI_DRAFT_COMPLETE";
export const TASK_GET_POI_DRAFT_END = "TASK_GET_POI_DRAFT_END";

export const TASK_WORKORDER_FOR_POI_START = "TASK_WORKORDER_FOR_POI_START";
export const TASK_WORKORDER_FOR_POI_COMPLETE = "TASK_WORKORDER_FOR_POI_COMPLETE";
export const TASK_WORKORDER_FOR_POI_END = "TASK_WORKORDER_FOR_POI_END";

export const TASK_WORKORDER_UN_FOR_POI_START = "TASK_WORKORDER_UN_FOR_POI_START";
export const TASK_WORKORDER_UN_FOR_POI_COMPLETE = "TASK_WORKORDER_UN_FOR_POI_COMPLETE";
export const TASK_WORKORDER_UN_FOR_POI_END = "TASK_WORKORDER_UN_FOR_POI_END";


export const TASK_WORKORDER_LINK_FOR_POI_START = "TASK_WORKORDER_LINK_FOR_POI_START";
export const TASK_WORKORDER_LINK_FOR_POI_COMPLETE = "TASK_WORKORDER_LINK_FOR_POI_COMPLETE";
export const TASK_WORKORDER_LINK_FOR_POI_END = "TASK_WORKORDER_LINK_FOR_POI_END";

export const TASK_GET_POI_BY_ID_START = "TASK_GET_POI_BY_ID_START";
export const TASK_GET_POI_BY_ID_COMPLETE = "TASK_GET_POI_BY_ID_COMPLETE";
export const TASK_GET_POI_BY_ID_END = "TASK_GET_POI_BY_ID_END";


export const TASK_GET_POI_BY_ID_START_DOC = "TASK_GET_POI_BY_ID_START_DOC";
export const TASK_GET_POI_BY_ID_COMPLETE_DOC = "TASK_GET_POI_BY_ID_COMPLETE_DOC";
export const TASK_GET_POI_BY_ID_END_DOC = "TASK_GET_POI_BY_ID_END_DOC";

export const TASK_POI_ARCHIVED_START = "TASK_POI_ARCHIVED_START";
export const TASK_POI_ARCHIVED_COMPLETE = "TASK_POI_ARCHIVED_COMPLETE";
export const TASK_POI_ARCHIVED_END = "TASK_POI_ARCHIVED_END";


export const TASK_GET_COMPANY_INFO_START = "TASK_GET_COMPANY_INFO_START";
export const TASK_GET_COMPANY_INFO_COMPLETE = "TASK_GET_COMPANY_INFO_COMPLETE";
export const TASK_GET_COMPANY_INFO_END = "TASK_GET_COMPANY_INFO_END";



export const TASK_GET_ADMIN_ALL_COMPANY_INFO_START = "TASK_GET_ADMIN_ALL_COMPANY_INFO_START";
export const TASK_GET_ADMIN_ALL_COMPANY_INFO_COMPLETE = "TASK_GET_ADMIN_ALL_COMPANY_INFO_COMPLETE";
export const TASK_GET_ADMIN_ALL_COMPANY_INFO_END = "TASK_GET_ADMIN_ALL_COMPANY_INFO_END";


export const TASK_EDIT_COMPANY_INFO_START = "TASK_EDIT_COMPANY_INFO_START";
export const TASK_EDIT_COMPANY_INFO_COMPLETE = "TASK_EDIT_COMPANY_INFO_COMPLETE";
export const TASK_EDIT_COMPANY_INFO_END = "TASK_EDIT_COMPANY_INFO_END";


// Projects
export const TASK_GET_PROJECT_START = "TASK_GET_PROJECT_START";
export const TASK_GET_PROJECT_COMPLETE = "TASK_GET_PROJECT_COMPLETE";
export const TASK_GET_PROJECT_ERROR = "TASK_GET_PROJECT_ERROR";
export const TASK_GET_PROJECT_END = "TASK_GET_PROJECT_END";


export const TASK_GET_ARCHIVED_PROJECT_START = "TASK_GET_ARCHIVED_PROJECT_START";
export const TASK_GET_ARCHIVED_PROJECT_COMPLETE = "TASK_GET_ARCHIVED_PROJECT_COMPLETE";
export const TASK_GET_ARCHIVED_PROJECT_ERROR = "TASK_GET_ARCHIVED_PROJECT_ERROR";
export const TASK_GET_ARCHIVED_PROJECT_END = "TASK_GET_ARCHIVED_PROJECT_END";


export const TASK_GET_DEPARTMENT_START = "TASK_GET_DEPARTMENT_START";
export const TASK_GET_DEPARTMENT_COMPLETE = "TASK_GET_DEPARTMENT_COMPLETE";
export const TASK_GET_DEPARTMENT_END = "TASK_GET_DEPARTMENT_END";

export const TASK_ADD_DEPARTMENT_START = "TASK_ADD_DEPARTMENT_START";
export const TASK_ADD_DEPARTMENT_COMPLETE = "TASK_ADD_DEPARTMENT_COMPLETE";
export const TASK_ADD_DEPARTMENT_END = "TASK_ADD_DEPARTMENT_END";


export const TASK_GET_CONTRACTOR_START = "TASK_GET_CONTRACTOR_START";
export const TASK_GET_CONTRACTOR_COMPLETE = "TASK_GET_CONTRACTOR_COMPLETE";
export const TASK_GET_CONTRACTOR_END = "TASK_GET_CONTRACTOR_END";



export const TASK_DELETE_CONTRACTOR_START = "TASK_DELETE_CONTRACTOR_START";
export const TASK_DELETE_CONTRACTOR_COMPLETE = "TASK_DELETE_CONTRACTOR_COMPLETE";
export const TASK_DELETE_CONTRACTOR_END = "TASK_DELETE_CONTRACTOR_END";


export const TASK_ADD_CONTRACTOR_START = "TASK_ADD_CONTRACTOR_START";
export const TASK_ADD_CONTRACTOR_COMPLETE = "TASK_ADD_CONTRACTOR_COMPLETE";
export const TASK_ADD_CONTRACTOR_END = "TASK_ADD_CONTRACTOR_END";


export const TASK_GET_PROJECT_DETAIL_START = "TASK_GET_PROJECT_DETAIL_START";
export const TASK_GET_PROJECT_DETAIL_COMPLETE = "TASK_GET_PROJECT_DETAIL_COMPLETE";
export const TASK_GET_PROJECT_DETAIL_END = "TASK_GET_PROJECT_DETAIL_END";


export const TASK_ARCHIVE_PROJECT_START = "TASK_ARCHIVE_PROJECT_START";
export const TASK_ARCHIVE_PROJECT_COMPLETE = "TASK_ARCHIVE_PROJECT_COMPLETE";
export const TASK_ARCHIVE_PROJECT_END = "TASK_ARCHIVE_PROJECT_END";

// Project

// Daily Project

export const TASK_GET_DAILY_PROJECT_START = "TASK_GET_DAILY_PROJECT_START";
export const TASK_GET_DAILY_PROJECT_COMPLETE = "TASK_GET_DAILY_PROJECT_COMPLETE";
export const TASK_GET_DAILY_PROJECT_END = "TASK_GET_DAILY_PROJECT_END";



export const TASK_GET_DAILY_PROJECT_DETAIL_START = "TASK_GET_DAILY_PROJECT_DETAIL_START";
export const TASK_GET_DAILY_PROJECT_DETAIL_COMPLETE = "TASK_GET_DAILY_PROJECT_DETAIL_COMPLETE";
export const TASK_GET_DAILY_PROJECT_DETAIL_END = "TASK_GET_DAILY_PROJECT_DETAIL_END";


export const TASK_DELETE_DAILY_PROJECT_START = "TASK_DELETE_DAILY_PROJECT_START";
export const TASK_DELETE_DAILY_PROJECT_COMPLETE = "TASK_DELETE_DAILY_PROJECT_COMPLETE";
export const TASK_DELETE_DAILY_PROJECT_END = "TASK_DELETE_DAILY_PROJECT_END";
// Alerts


export const TASK_GET_ALERTS_START = "TASK_GET_ALERTS_START";
export const TASK_GET_ALERTS_COMPLETE = "TASK_GET_ALERTS_COMPLETE";
export const TASK_GET_ALERTS_ERROR = "TASK_GET_ALERTS_ERROR";
export const TASK_GET_ALERTS_END = "TASK_GET_ALERTS_END";

export const TASK_GET_ARCHIVED_ALERTS_START = "TASK_GET_ARCHIVED_ALERTS_START";
export const TASK_GET_ARCHIVED_ALERTS_COMPLETE = "TASK_GET_ARCHIVED_ALERTS_COMPLETE";
export const TASK_GET_ARCHIVED_ALERTS_ERROR = "TASK_GET_ARCHIVED_ALERTS_ERROR";
export const TASK_GET_ARCHIVED_ALERTS_END = "TASK_GET_ARCHIVED_ALERTS_END";

export const TASK_GET_ALERTS_DETAIL_START = "TASK_GET_ALERTS_DETAIL_START";
export const TASK_GET_ALERTS_DETAIL_COMPLETE = "TASK_GET_ALERTS_DETAIL_COMPLETE";
export const TASK_GET_ALERTS_DETAIL_END = "TASK_GET_ALERTS_DETAIL_END";

export const TASK_ARCHIVE_ALERTS_START = "TASK_ARCHIVE_ALERTS_START";
export const TASK_ARCHIVE_ALERTS_COMPLETE = "TASK_ARCHIVE_ALERTS_COMPLETE";
export const TASK_ARCHIVE_ALERTS_END = "TASK_ARCHIVE_ALERTS_END";





// Assets


export const TASK_GET_ASSETS_START = "TASK_GET_ASSETS_START";
export const TASK_GET_ASSETS_COMPLETE = "TASK_GET_ASSETS_COMPLETE";
export const TASK_GET_ASSETS_ERROR = "TASK_GET_ASSETS_ERROR";
export const TASK_GET_ASSETS_END = "TASK_GET_ASSETS_END";

export const TASK_GET_ARCHIVED_ASSETS_START = "TASK_GET_ARCHIVED_ASSETS_START";
export const TASK_GET_ARCHIVED_ASSETS_COMPLETE = "TASK_GET_ARCHIVED_ASSETS_COMPLETE";
export const TASK_GET_ARCHIVED_ASSETS_ERROR = "TASK_GET_ARCHIVED_ASSETS_ERROR";
export const TASK_GET_ARCHIVED_ASSETS_END = "TASK_GET_ARCHIVED_ASSETS_END";

export const TASK_ARCHIVE_ASSETS_START = "TASK_ARCHIVE_ASSETS_START";
export const TASK_ARCHIVE_ASSETS_COMPLETE = "TASK_ARCHIVE_ASSETS_COMPLETE";
export const TASK_ARCHIVE_ASSETS_END = "TASK_ARCHIVE_ASSETS_END";

export const TASK_GET_MODEL_START = "TASK_GET_MODEL_START";
export const TASK_GET_MODEL_COMPLETE = "TASK_GET_MODEL_COMPLETE";
export const TASK_GET_MODEL_END = "TASK_GET_MODEL_END";

export const TASK_GET_ASSET_TYPE_START = "TASK_GET_ASSET_TYPE_START";
export const TASK_GET_ASSET_TYPE_COMPLETE = "TASK_GET_ASSET_TYPE_COMPLETE";
export const TASK_GET_ASSET_TYPE_END = "TASK_GET_ASSET_TYPE_END";

export const TASK_GET_ASSET_DETAIL_START = "TASK_GET_ASSET_DETAIL_START";
export const TASK_GET_ASSET_DETAIL_COMPLETE = "TASK_GET_ASSET_DETAIL_COMPLETE";
export const TASK_GET_ASSET_DETAIL_END = "TASK_GET_ASSET_DETAIL_END";


// worksite

export const TASK_CREATE_WORKSITE_START = "TASK_CREATE_WORKSITE_START";
export const TASK_CREATE_WORKSITE_COMPLETE = "TASK_CREATE_WORKSITE_COMPLETE";
export const TASK_CREATE_WORKSITE_END = "TASK_CREATE_WORKSITE_END";


export const TASK_LOAD_WORKSITE_START = "TASK_LOAD_WORKSITE_START";
export const TASK_LOAD_WORKSITE_COMPLETE = "TASK_LOAD_WORKSITE_COMPLETE";
export const TASK_LOAD_WORKSITE_END = "TASK_LOAD_WORKSITE_END";

export const TASK_LOAD_WORKSITE_DETAIL_START = "TASK_LOAD_WORKSITE_DETAIL_START";
export const TASK_LOAD_WORKSITE_DETAIL_COMPLETE = "TASK_LOAD_WORKSITE_DETAIL_COMPLETE";
export const TASK_LOAD_WORKSITE_DETAIL_END = "TASK_LOAD_WORKSITE_DETAIL_END";

export const TASK_LOAD_MANAGER_START = "TASK_LOAD_MANAGER_START";
export const TASK_LOAD_MANAGER_COMPLETE = "TASK_LOAD_MANAGER_COMPLETE";
export const TASK_LOAD_MANAGER_END = "TASK_LOAD_MANAGER_END";


export const TASK_LOAD_MUSTER_STATION_START = "TASK_LOAD_MUSTER_STATION_START";
export const TASK_LOAD_MUSTER_STATION_COMPLETE = "TASK_LOAD_MUSTER_STATION_COMPLETE";
export const TASK_LOAD_MUSTER_STATION_END = "TASK_LOAD_MUSTER_STATION_END";


export const TASK_LOAD_WORKSITE_TEAM_START = "TASK_LOAD_WORKSITE_TEAM_START";
export const TASK_LOAD_WORKSITE_TEAM_COMPLETE = "TASK_LOAD_WORKSITE_TEAM_COMPLETE";
export const TASK_LOAD_WORKSITE_TEAM_END = "TASK_LOAD_WORKSITE_TEAM_END";



// Evacuate
export const TASK_LOAD_EVACUATE_START = "TASK_LOAD_EVACUATE_START";
export const TASK_LOAD_EVACUATE_COMPLETE = "TASK_LOAD_EVACUATE_COMPLETE";
export const TASK_LOAD_EVACUATE_END = "TASK_LOAD_EVACUATE_END";



// NewUIPART

export const MESSAGE_SHOW = "MESSAGE_SHOW";
export const MESSAGE_HIDE = "MESSAGE_HIDE";
